name: Chromatic
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install
        run: yarn install --frozen-lockfile
      - name: Run Chromatic
        id: run-chromatic-action
        uses: chromaui/action-next@v1
        with:
          exitOnceUploaded: true
          exitOnZeroChanges: true
          onlyChanged: true
          traceChanged: true
          diagnostics: true
          autoAcceptChanges: "main"
          buildScriptName: "build:storybook"
        env:
          CHROMATIC_PROJECT_TOKEN: gcaw1ai2dgo
          STORYBOOK_GITHUB_SHA: ${{ github.event.pull_request.head.sha }}

      - name: "Chromatic outputs"
        run: echo ${{steps.run-chromatic-action.outputs.code}}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: chromatic-build-artifacts-${{ github.run_id }}
          path: |
            chromatic-diagnostics.json
            **/build-storybook.log
